name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action'
        required: true
        default: 'plan-apply'
        type: choice
        options:
          - plan-apply
          - destroy

env:
  AWS_REGION: "us-east-1"
  TF_VERSION: "1.5.0"

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:

  terraform:
    name: Terraform Plan/Apply
    if: github.event.inputs.action == 'plan-apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::877786395093:role/github-oidc-vamsee
          aws-region: ap-south-1
          id-token: true

      - name: Terraform Init
        run: |
          cd infra
          terraform init

      - name: Terraform Validate
        run: |
          cd infra
          terraform validate

      - name: Terraform Plan
        run: |
          cd infra
          terraform plan -var-file="../env/dev/terraform.tfvars" -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd infra
          terraform apply -auto-approve tfplan

  destroy:
    name: Terraform Destroy
    if: github.event.inputs.action == 'destroy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::877786395093:role/github-oidc-vamsee
          aws-region: ap-south-1
          id-token: true

      - name: Terraform Init
        run: |
          cd infra
          terraform init

      - name: Terraform Destroy
        run: |
          cd infra
          terraform destroy -auto-approve -var-file="../env/dev/terraform.tfvars"
